export const realEstate = [
  {
    userPost: "62b57b3833055da7c06c9d06",
    userApprove: "62b57b3833055da7c06c9d06",
    method: "Bán",
    title:
      "THE GRAND MANHATTAN - BÁN GẤP CĂN HỘ 2 PHÒNG NGỦ 71M2 VIEW SÔNG SAIGON VÀ TT SG BITEXCO",
    subTitle:
      "Dự án The Grand Manhattan, Đường Cô Giang, Phường Cô Giang, Quận 1, Hồ Chí Minh",
    images: [
      "image-1-1.jpg",
      "image-1-2.jpg",
      "image-1-3.jpg",
      "image-1-4.jpg",
    ],
    startDay: "2022-06-22",
    endDay: "2022-07-22",
    address: "",
    area: 71,
    price: 14.5,
    desc: "Cần bán gấp căn hộ cao cấp The Grand Manhattan tại 100 Cô Bắc - Cô Giang, Quận 1.\nDiện tích: 71m2, thiết kế 2 phòng ngủ.\nHướng Đông Nam.\nView TT Sài Gòn Bitexcon và Sông Sài Gòn.\nGiao nhà hoàn thiện cơ bản, có gói Smart Home.\nChỉ thanh toán 30%, tới tháng 12/2022 mới thanh toán tiếp.\nNhận nhà: Tháng 11/2023.\nTiến độ xây dựng: Đã lên sàn tầng 6.\nDự án duy nhất tại Trung tâm Quận 1 có 5 tầng khách sạn Quốc Tế do tập đoàn Avani quản lý và vận hàng.\nĐã có nhà mẫu để tham quan.",
    bedRoom: 2,
    toiletRoom: 3,
    floors: 5,
    juridical: "Hợp đồng mua bán",
  },
  {
    userPost: "62b57b3833055da7c06c9d06",
    userApprove: "62b57b3833055da7c06c9d06",
    method: "Bán",
    title:
      "LÀM VIỆC CHÍNH CHỦ, XEM NHÀ NGAY KHÔNG PHẢI CHỜ, 50 CĂN MỚI ĐÃ CÓ SỔ HỒNG GIÁ CHỈ 1.750 TỶ/CĂN",
    subTitle: "Dự án Căn hộ Ricca Quận 9, Quận 9, Hồ Chí Minh",
    images: [
      "image2-1.jpg",
      "image2-2.jpg",
      "image2-3.jpg",
      "image2-4.jpg",
      "image2-5.jpg",
    ],
    startDay: "2022-06-24",
    endDay: "2022-07-25",
    address: "",
    area: 56,
    price: 1.75,
    desc: "Cần bán gấp căn hộ cao cấp The Grand Manhattan tại 100 Cô Bắc - Cô Giang, Quận 1.\nDiện tích: 71m2, thiết kế 2 phòng ngủ.\nHướng Đông Nam.\nView TT Sài Gòn Bitexcon và Sông Sài Gòn.\nGiao nhà hoàn thiện cơ bản, có gói Smart Home.\nChỉ thanh toán 30%, tới tháng 12/2022 mới thanh toán tiếp.\nNhận nhà: Tháng 11/2023.\nTiến độ xây dựng: Đã lên sàn tầng 6.\nDự án duy nhất tại Trung tâm Quận 1 có 5 tầng khách sạn Quốc Tế do tập đoàn Avani quản lý và vận hàng.\nĐã có nhà mẫu để tham quan.",
    bedRoom: 2,
    toiletRoom: 3,
    floors: 5,
    juridical: "Hợp đồng mua bán",
  },
  {
    userPost: "62b57b3833055da7c06c9d06",
    userApprove: "62b57b3833055da7c06c9d06",
    method: "Bán",
    title:
      "GIÁ TỪ 31. TRĐ/M2 CHỈ 2 CĂN 2N + 1 (1WC) VINHOMES SMART CITY GIÁ TỐT NHẤT TRONG DỰ ÁN, HỖ TRỢ 80%",
    subTitle: "Dự án Vinhomes Smart City , Quận Nam Từ Liêm, Hà Nội",
    images: [
      "image3-1.jpg",
      "image3-2.jpg",
      "image3-3.jpg",
      "image3-4.jpg",
      "image3-5.jpg",
    ],
    startDay: "2022-06-24",
    endDay: "2022-07-25",
    address: "",
    area: 64,
    price: 6.75,
    desc: "Cần bán gấp căn hộ cao cấp The Grand Manhattan tại 100 Cô Bắc - Cô Giang, Quận 1.\nDiện tích: 71m2, thiết kế 2 phòng ngủ.\nHướng Đông Nam.\nView TT Sài Gòn Bitexcon và Sông Sài Gòn.\nGiao nhà hoàn thiện cơ bản, có gói Smart Home.\nChỉ thanh toán 30%, tới tháng 12/2022 mới thanh toán tiếp.\nNhận nhà: Tháng 11/2023.\nTiến độ xây dựng: Đã lên sàn tầng 6.\nDự án duy nhất tại Trung tâm Quận 1 có 5 tầng khách sạn Quốc Tế do tập đoàn Avani quản lý và vận hàng.\nĐã có nhà mẫu để tham quan.",
    bedRoom: 3,
    toiletRoom: 2,
    floors: 3,
    juridical: "Hợp đồng mua bán",
  },
  {
    userPost: "62b57b3833055da7c06c9d06",
    userApprove: "62b57b3833055da7c06c9d06",
    method: "Bán",
    title:
      "CHÍNH CHỦ BÁN CHUNG CƯ LK Q2 SỔ RIÊNG, CĂN GÓC DT 70M2 CÓ 2PN, 2WC, VIEW LANDMARK 81 GIÁ 2,3 TỶ",
    subTitle:
      "Dự án Căn hộ Ricca Quận 9, Đường Gò Cát, Phường Phú Hữu, Quận 9, Hồ Chí Minh",
    images: [
      "image4-1.jpg",
      "image4-2.jpg",
      "image4-3.jpg",
      "image4-4.jpg",
      "image4-5.jpg",
    ],
    startDay: "2022-06-24",
    endDay: "2022-07-25",
    address: "",
    area: 70,
    price: 2.5,
    desc: "Cần bán gấp căn hộ cao cấp The Grand Manhattan tại 100 Cô Bắc - Cô Giang, Quận 1.\nDiện tích: 71m2, thiết kế 2 phòng ngủ.\nHướng Đông Nam.\nView TT Sài Gòn Bitexcon và Sông Sài Gòn.\nGiao nhà hoàn thiện cơ bản, có gói Smart Home.\nChỉ thanh toán 30%, tới tháng 12/2022 mới thanh toán tiếp.\nNhận nhà: Tháng 11/2023.\nTiến độ xây dựng: Đã lên sàn tầng 6.\nDự án duy nhất tại Trung tâm Quận 1 có 5 tầng khách sạn Quốc Tế do tập đoàn Avani quản lý và vận hàng.\nĐã có nhà mẫu để tham quan.",
    bedRoom: 2,
    toiletRoom: 2,
    floors: 3,
    juridical: "Hợp đồng mua bán",
  },
  {
    userPost: "62b57b3833055da7c06c9d06",
    userApprove: "62b57b3833055da7c06c9d06",
    method: "Bán",
    title:
      "[LÀNG MÂY LỘC NGÃI 2] - ĐẤT BẢO LÂM CHỈ TỪ 1.2 TRIỆU /M2 GẦN NOVALAND, HÌNH ẢNH VÀ THÔNG TIN THẬT",
    subTitle: "Đường ĐT 725, Xã Lộc Ngãi, Bảo Lâm, Lâm Đồng",
    images: ["image5-1.jpg", "image5-2.jpg", "image5-3.jpg", "image5-4.jpg"],
    startDay: "2022-06-24",
    endDay: "2022-07-25",
    address: "",
    area: 150,
    price: 4,
    desc: "Cần bán gấp căn hộ cao cấp The Grand Manhattan tại 100 Cô Bắc - Cô Giang, Quận 1.\nDiện tích: 71m2, thiết kế 2 phòng ngủ.\nHướng Đông Nam.\nView TT Sài Gòn Bitexcon và Sông Sài Gòn.\nGiao nhà hoàn thiện cơ bản, có gói Smart Home.\nChỉ thanh toán 30%, tới tháng 12/2022 mới thanh toán tiếp.\nNhận nhà: Tháng 11/2023.\nTiến độ xây dựng: Đã lên sàn tầng 6.\nDự án duy nhất tại Trung tâm Quận 1 có 5 tầng khách sạn Quốc Tế do tập đoàn Avani quản lý và vận hàng.\nĐã có nhà mẫu để tham quan.",
    bedRoom: 2,
    toiletRoom: 2,
    floors: 3,
    juridical: "Hợp đồng mua bán",
  },
  {
    userPost: "62b57b3833055da7c06c9d06",
    userApprove: "62b57b3833055da7c06c9d06",
    method: "Bán",
    title:
      "BẢNG GIÁ SUNRISE CITY- CITY VIEW CẬP NHẬT GIÁ BÁN T4.2022 -1PN-2.55TỶ, 2PN-3.5TỶ, 3PN-4.3TỶ",
    subTitle:
      "Dự án Sunrise City, Đường Nguyễn Hữu Thọ, Phường Tân Hưng, Quận 7, Hồ Chí Minh",
    images: [
      "image6-1.jpg",
      "image6-2.jpg",
      "image6-3.jpg",
      "image6-4.jpg",
      "image6-5.jpg",
    ],
    startDay: "2022-06-24",
    endDay: "2022-07-25",
    address: "",
    area: 106,
    price: 4.2,
    desc: "Cần bán gấp căn hộ cao cấp The Grand Manhattan tại 100 Cô Bắc - Cô Giang, Quận 1.\nDiện tích: 71m2, thiết kế 2 phòng ngủ.\nHướng Đông Nam.\nView TT Sài Gòn Bitexcon và Sông Sài Gòn.\nGiao nhà hoàn thiện cơ bản, có gói Smart Home.\nChỉ thanh toán 30%, tới tháng 12/2022 mới thanh toán tiếp.\nNhận nhà: Tháng 11/2023.\nTiến độ xây dựng: Đã lên sàn tầng 6.\nDự án duy nhất tại Trung tâm Quận 1 có 5 tầng khách sạn Quốc Tế do tập đoàn Avani quản lý và vận hàng.\nĐã có nhà mẫu để tham quan.",
    bedRoom: 3,
    toiletRoom: 3,
    floors: 3,
    juridical: "Hợp đồng mua bán",
  },
  {
    userPost: "62b57b3833055da7c06c9d06",
    userApprove: "62b57b3833055da7c06c9d06",
    method: "Bán",
    title:
      "THẬT 100% - BÁN GẤP CĂN HỘ SỔ HỒNG, 1PN - 2.6 TỶ/2PN - 3.8 TỶ/3PN - 5.1 TỶ TẠI SUNRISE CITY QUẬN 7",
    subTitle:
      "Dự án Sunrise City, Đường Nguyễn Hữu Thọ, Phường Tân Hưng, Quận 7, Hồ Chí Minh",
    images: [
      "image7-1.jpg",
      "image7-2.jpg",
      "image7-3.jpg",
      "image7-4.jpg",
      "image7-5.jpg",
    ],
    startDay: "2022-06-24",
    endDay: "2022-07-25",
    address: "",
    area: 124,
    price: 5.6,
    desc: "Cần bán gấp căn hộ cao cấp The Grand Manhattan tại 100 Cô Bắc - Cô Giang, Quận 1.\nDiện tích: 71m2, thiết kế 2 phòng ngủ.\nHướng Đông Nam.\nView TT Sài Gòn Bitexcon và Sông Sài Gòn.\nGiao nhà hoàn thiện cơ bản, có gói Smart Home.\nChỉ thanh toán 30%, tới tháng 12/2022 mới thanh toán tiếp.\nNhận nhà: Tháng 11/2023.\nTiến độ xây dựng: Đã lên sàn tầng 6.\nDự án duy nhất tại Trung tâm Quận 1 có 5 tầng khách sạn Quốc Tế do tập đoàn Avani quản lý và vận hàng.\nĐã có nhà mẫu để tham quan.",
    bedRoom: 3,
    toiletRoom: 3,
    floors: 3,
    juridical: "Hợp đồng mua bán",
  },
  {
    userPost: "62b57b3833055da7c06c9d06",
    userApprove: "62b57b3833055da7c06c9d06",
    method: "Bán",
    title:
      "CHUYÊN BÁN CĂN HỘ 1 - 2 - 3 - 4PN VINHOMES CENTRAL PARK GIÁ TỐT NHẤT. LH TIẾN HẢI 0906515755",
    subTitle:
      "Dự án Vinhomes Central Park, Đường Điện Biên Phủ, Phường 22, Bình Thạnh, Hồ Chí Minh",
    images: [
      "image8-1.jpg",
      "image8-2.jpg",
      "image8-3.jpg",
      "image8-4.jpg",
      "image8-5.jpg",
    ],
    startDay: "2022-06-24",
    endDay: "2022-07-25",
    address: "",
    area: 83,
    price: 4.4,
    desc: "Cần bán gấp căn hộ cao cấp The Grand Manhattan tại 100 Cô Bắc - Cô Giang, Quận 1.\nDiện tích: 71m2, thiết kế 2 phòng ngủ.\nHướng Đông Nam.\nView TT Sài Gòn Bitexcon và Sông Sài Gòn.\nGiao nhà hoàn thiện cơ bản, có gói Smart Home.\nChỉ thanh toán 30%, tới tháng 12/2022 mới thanh toán tiếp.\nNhận nhà: Tháng 11/2023.\nTiến độ xây dựng: Đã lên sàn tầng 6.\nDự án duy nhất tại Trung tâm Quận 1 có 5 tầng khách sạn Quốc Tế do tập đoàn Avani quản lý và vận hàng.\nĐã có nhà mẫu để tham quan.",
    bedRoom: 3,
    toiletRoom: 3,
    floors: 3,
    juridical: "Hợp đồng mua bán",
  },
]
